version: '3.8'

services:
  # Frontend (React)
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  # Backend (Python FastAPI)
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/multilingual-forum
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - server/.env
    volumes:
      - ./server:/app
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  # Database (MongoDB)
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=multilingual-forum
    restart: unless-stopped

  # Redis for caching translations
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:

networks:
  default:
    driver: bridge 