services:
  - type: web
    name: multilingual-forum-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: cd server && pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: cd server && python main-simple.py
          envVars:
        - key: PYTHON_VERSION
          value: 3.11.0
        - key: NODE_ENV
          value: production
        - key: ALLOWED_ORIGINS
          value: https://multilingual-forum.vercel.app
    healthCheckPath: /api/health 