services:
  - type: web
    name: multilingual-forum-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: cd server && pip install --upgrade pip && pip install -r requirements-ultra.txt
    startCommand: cd server && python main-ultra-simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://multilingual-forum.vercel.app,https://*.vercel.app
      - key: PORT
        value: 10000
    healthCheckPath: /api/health 